export interface User {
  id: string;
  email: string;
  name: string;
  oab?: string;
  acceptedLegalDisclaimer: boolean;
  avatarUrl?: string;
}

export enum PetitionStatus {
  DRAFT = 'Rascunho',
  REVIEW = 'Em Revisão',
  COMPLETED = 'Finalizado',
}

export interface CnjMetadata {
  classe: string;
  codigoClasse: string;
  assunto: string;
  codigoAssunto: string;
  competencia?: string; // Field added for jurisdiction suggestion
  valorCausa?: string;
  resumo?: string;
}

export interface Petition {
  id: string;
  title: string;
  type: string;
  clientName: string;
  createdAt: string;
  updatedAt: string;
  status: PetitionStatus;
  content?: string; // Content generated by AI or edited by user
  cnjData?: CnjMetadata; // AI analyzed data for filing
}

export interface PetitionDraft {
  actionType: string;
  plaintiff: string; // Requerente
  defendant: string; // Requerido
  facts: string;
  requests: string[]; // Pedidos
  jurisdiction?: string; // Foro
}

export interface FilingData {
  court: string; // Foro/Tribunal
  competency: string; // Competência
  class: string; // Classe Judicial
  subject: string; // Assunto
}

export interface GroundingSource {
  title: string;
  uri: string;
}

export interface JurisprudenceResult {
  analysis: string;
  sources: GroundingSource[];
}

export interface LegalDeadline {
  id: string;
  processNumber: string;
  description: string;
  deadlineDate: string; // ISO Date YYYY-MM-DD
  notifyDaysBefore: number;
  isCompleted: boolean;
}